-- 0051: re-seed master hobbies dengan katalog SOHO (English + emoji).
-- Hapus seed lama (Indonesia) lalu isi katalog baru. Nilai profiles.hobbies[]
-- milik user TETAP (ini cuma master pilihan yg bisa dipilih).

DELETE FROM hobbies;
DELETE FROM hobby_categories;

INSERT INTO hobby_categories (name, sort_order) VALUES
  ('Food & Drink', 10),
  ('Music', 20),
  ('Going Out', 30),
  ('Games & Play', 40),
  ('Sports & Fitness', 50),
  ('Culture & Creativity', 60),
  ('Lifestyle', 70)
ON CONFLICT (name) DO UPDATE SET sort_order = EXCLUDED.sort_order;

INSERT INTO hobbies (name, category, emoji, sort_order) VALUES
  ('Cocktails', 'Food & Drink', '🍸', 10),
  ('Wine', 'Food & Drink', '🍷', 20),
  ('Craft beer', 'Food & Drink', '🍺', 30),
  ('Whiskey', 'Food & Drink', '🥃', 40),
  ('Coffee', 'Food & Drink', '☕', 50),
  ('Mixology', 'Food & Drink', '🧪', 60),
  ('Foodie', 'Food & Drink', '😋', 70),
  ('Barbecue', 'Food & Drink', '🍖', 80),
  ('Sushi', 'Food & Drink', '🍣', 90),
  ('Ramen', 'Food & Drink', '🍜', 100),
  ('Pizza', 'Food & Drink', '🍕', 110),
  ('Tacos', 'Food & Drink', '🌮', 120),
  ('Desserts', 'Food & Drink', '🍫', 130),
  ('Shisha', 'Food & Drink', '💨', 140),
  ('Tea', 'Food & Drink', '🍵', 150),
  ('Vegan', 'Food & Drink', '🌱', 160),
  ('Live music', 'Music', '🎤', 10),
  ('DJ sets', 'Music', '🎧', 20),
  ('House', 'Music', '🎵', 30),
  ('EDM', 'Music', '🎵', 40),
  ('Hip-hop', 'Music', '🎵', 50),
  ('R&B', 'Music', '🎵', 60),
  ('Jazz', 'Music', '🎷', 70),
  ('Indie', 'Music', '🎸', 80),
  ('Rock', 'Music', '🎸', 90),
  ('Pop', 'Music', '🎵', 100),
  ('Techno', 'Music', '🎛️', 110),
  ('Vinyl', 'Music', '💿', 120),
  ('K-pop', 'Music', '🎵', 130),
  ('Latin', 'Music', '🎵', 140),
  ('Grabbing a drink', 'Going Out', '🥂', 10),
  ('Nightclubs', 'Going Out', '🪩', 20),
  ('Karaoke', 'Going Out', '🎤', 30),
  ('Concerts', 'Going Out', '🎟️', 40),
  ('Festivals', 'Going Out', '🎉', 50),
  ('Comedy shows', 'Going Out', '🎙️', 60),
  ('Cafe-hopping', 'Going Out', '☕', 70),
  ('Dining out', 'Going Out', '🍽️', 80),
  ('Trivia', 'Going Out', '🧠', 90),
  ('Open mic', 'Going Out', '🎤', 100),
  ('Billiard', 'Games & Play', '🎱', 10),
  ('Darts', 'Games & Play', '🎯', 20),
  ('Board games', 'Games & Play', '♟️', 30),
  ('Video games', 'Games & Play', '🎮', 40),
  ('Poker', 'Games & Play', '🃏', 50),
  ('Watch parties', 'Games & Play', '📺', 60),
  ('Gym', 'Sports & Fitness', '💪', 10),
  ('Football', 'Sports & Fitness', '⚽', 20),
  ('Basketball', 'Sports & Fitness', '🏀', 30),
  ('Running', 'Sports & Fitness', '🏃', 40),
  ('Cycling', 'Sports & Fitness', '🚴', 50),
  ('Yoga', 'Sports & Fitness', '🧘', 60),
  ('Boxing', 'Sports & Fitness', '🥊', 70),
  ('Swimming', 'Sports & Fitness', '🏊', 80),
  ('Climbing', 'Sports & Fitness', '🧗', 90),
  ('Tennis', 'Sports & Fitness', '🎾', 100),
  ('Photography', 'Culture & Creativity', '📷', 10),
  ('Art', 'Culture & Creativity', '🎨', 20),
  ('Fashion', 'Culture & Creativity', '👗', 30),
  ('Design', 'Culture & Creativity', '✨', 40),
  ('Movies', 'Culture & Creativity', '🎬', 50),
  ('Anime', 'Culture & Creativity', '🌸', 60),
  ('Reading', 'Culture & Creativity', '📚', 70),
  ('Dance', 'Culture & Creativity', '💃', 80),
  ('Plays instrument', 'Culture & Creativity', '🎹', 90),
  ('Singing', 'Culture & Creativity', '🎙️', 100),
  ('Tattoos', 'Culture & Creativity', '⚓', 110),
  ('Writing', 'Culture & Creativity', '✏️', 120),
  ('Travel', 'Lifestyle', '✈️', 10),
  ('Big cities', 'Lifestyle', '🏙️', 20),
  ('Beach', 'Lifestyle', '🏖️', 30),
  ('Road trips', 'Lifestyle', '🛣️', 40),
  ('Networking', 'Lifestyle', '🤝', 50),
  ('Meeting new people', 'Lifestyle', '👋', 60),
  ('Entrepreneurship', 'Lifestyle', '🚀', 70),
  ('Wellness', 'Lifestyle', '🌿', 80),
  ('Pets', 'Lifestyle', '🐾', 90),
  ('Volunteering', 'Lifestyle', '💗', 100)
ON CONFLICT (name) DO UPDATE SET category = EXCLUDED.category, emoji = EXCLUDED.emoji, sort_order = EXCLUDED.sort_order;
